import { ReactNode } from "react";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar/Navbar";
import { Coiny, Quicksand, Open_Sans } from "next/font/google";
import "./globals.css";

const coiny = Coiny({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-title"
});
const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-heading"
});
const openSans = Open_Sans({ 
  subsets: ["latin"],
  variable: "--font-body"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode; }) => {
  return (
    <html lang="en">
      <body className={`${coiny.variable} ${quicksand.variable} ${openSans.variable}`}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
};
export default RootLayout;
